import 'crossword_puzzle.dart';

final puzzleDemoDicht = CrosswordPuzzle(
  id: 'demo_dicht_15x15',
  title: 'Sein, Wert und Polis',
  theme: 'Ontologie, Ethik und politische Ordnung im dichten Gitter',
  gridRows: 15,
  gridCols: 15,
  difficulty: 'Anspruchsvoll',
  estimatedMinutes: 12,
  sourceLabel: 'Themenrätsel · Begriffe',
  words: [
    const CrosswordWord(
      id: 'dicht_platon_a',
      answer: 'PLATON',
      clue: 'Griechischer Philosoph der Ideenlehre.',
      row: 8,
      col: 4,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_welt_d',
      answer: 'WELT',
      clue: 'Bei Wittgenstein: alles, was der Fall ist.',
      row: 5,
      col: 7,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_zeit_a',
      answer: 'ZEIT',
      clue: 'Grundform der Erfahrung neben dem Raum.',
      row: 6,
      col: 6,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_wert_d',
      answer: 'WERT',
      clue: 'Was in Ethik und Ästhetik zählt.',
      row: 3,
      col: 9,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_nous_d',
      answer: 'NOUS',
      clue: 'Griechisch für Geist oder Vernunft.',
      row: 8,
      col: 9,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_sein_a',
      answer: 'SEIN',
      clue: 'Grundbegriff der Ontologie.',
      row: 4,
      col: 8,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_ding_d',
      answer: 'DING',
      clue: 'Bei Kant gibt es es auch „an sich“.',
      row: 2,
      col: 11,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_akt_d',
      answer: 'AKT',
      clue: 'Vollzug im Gegensatz zur Möglichkeit.',
      row: 8,
      col: 6,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_sinn_a',
      answer: 'SINN',
      clue: 'Bedeutung oder Verstehensrichtung.',
      row: 11,
      col: 9,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_gut_a',
      answer: 'GUT',
      clue: 'Zentraler Wertbegriff der Ethik.',
      row: 10,
      col: 4,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_arendt_d',
      answer: 'ARENDT',
      clue: 'Denkerin der „Banalität des Bösen“.',
      row: 8,
      col: 11,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_dike_a',
      answer: 'DIKE',
      clue: 'Griechisch: Recht oder Gerechtigkeit.',
      row: 2,
      col: 11,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_rede_a',
      answer: 'REDE',
      clue: 'Gesprochenes Wort; wichtig im Dialog.',
      row: 9,
      col: 11,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_eros_d',
      answer: 'EROS',
      clue: 'Bei Platon: Liebe oder Begehren.',
      row: 9,
      col: 14,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_telos_d',
      answer: 'TELOS',
      clue: 'Griechisch für Ziel oder Zweck.',
      row: 1,
      col: 14,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_mut_a',
      answer: 'MUT',
      clue: 'Tugend im Umgang mit Gefahr.',
      row: 13,
      col: 9,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_genus_d',
      answer: 'GENUS',
      clue: 'Lateinisch: Gattung.',
      row: 10,
      col: 4,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_nexus_a',
      answer: 'NEXUS',
      clue: 'Gelehrtes Wort für Zusammenhang.',
      row: 12,
      col: 4,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_ehre_a',
      answer: 'EHRE',
      clue: 'Anerkennung oder guter Ruf.',
      row: 11,
      col: 1,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_hyle_d',
      answer: 'HYLE',
      clue: 'Griechisch: Stoff oder Materie.',
      row: 8,
      col: 1,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_hexis_a',
      answer: 'HEXIS',
      clue: 'Aristotelisch: erworbene Haltung.',
      row: 14,
      col: 0,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_lust_d',
      answer: 'LUST',
      clue: 'Bei Epikur: nicht bloß Party, sondern Schmerzfreiheit.',
      row: 11,
      col: 7,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_leid_d',
      answer: 'LEID',
      clue: 'Ausgangspunkt der vier edlen Wahrheiten.',
      row: 6,
      col: 13,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_prinzip_d',
      answer: 'PRINZIP',
      clue: 'Grundsatz oder Anfangsgrund.',
      row: 2,
      col: 4,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_teil_a',
      answer: 'TEIL',
      clue: 'Gegenstück zum Ganzen.',
      row: 4,
      col: 2,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_atman_d',
      answer: 'ATMAN',
      clue: 'Sanskrit-Begriff für das Selbst.',
      row: 3,
      col: 2,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_polis_a',
      answer: 'POLIS',
      clue: 'Griechischer Stadtstaat.',
      row: 2,
      col: 4,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_volk_d',
      answer: 'VOLK',
      clue: 'Politisches Kollektiv; in Demokratien souverän.',
      row: 0,
      col: 6,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_relativismus_a',
      answer: 'RELATIVISMUS',
      clue: 'Position: Wahrheit oder Werte gelten nur relativ.',
      row: 0,
      col: 0,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_ren_a',
      answer: 'REN',
      clue: 'Konfuzianische Menschlichkeit.',
      row: 7,
      col: 12,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'dicht_regel_d',
      answer: 'REGEL',
      clue: 'Vorschrift, nach der etwas abläuft.',
      row: 0,
      col: 0,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'dicht_satz_a',
      answer: 'SATZ',
      clue: 'Aussage aus Wörtern; in der Logik wichtig.',
      row: 6,
      col: 1,
      direction: WordDirection.across,
    ),
  ],
);

final puzzleDemoKompakt = CrosswordPuzzle(
  id: 'demo_kompakt_15x15',
  title: 'Vernunft und Lebensform',
  theme: 'Kantische Begriffe, Sprache und Existenz in kompakter Mitte',
  gridRows: 15,
  gridCols: 15,
  difficulty: 'Mittel',
  estimatedMinutes: 10,
  sourceLabel: 'Themenrätsel · Begriffe',
  words: [
    const CrosswordWord(
      id: 'kompakt_vernunft_d',
      answer: 'VERNUNFT',
      clue: 'Vermögen des begründenden Denkens.',
      row: 1,
      col: 7,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_volk_a',
      answer: 'VOLK',
      clue: 'Politisches Kollektiv; in Demokratien souverän.',
      row: 1,
      col: 7,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_name_a',
      answer: 'NAME',
      clue: 'Sprachlicher Bezug auf eine Person oder Sache.',
      row: 6,
      col: 7,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_mitte_a',
      answer: 'MITTE',
      clue: 'Bei Aristoteles liegt die Tugend oft dort.',
      row: 8,
      col: 5,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_imperativ_d',
      answer: 'IMPERATIV',
      clue: 'Bei Kant gibt es ihn kategorisch.',
      row: 5,
      col: 9,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_form_d',
      answer: 'FORM',
      clue: 'Gegenstück zum Stoff, besonders bei Aristoteles.',
      row: 5,
      col: 5,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_term_a',
      answer: 'TERM',
      clue: 'Ausdruck oder Baustein in der Logik.',
      row: 3,
      col: 5,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_actus_a',
      answer: 'ACTUS',
      clue: 'Lateinisch: Wirklichkeit oder Vollzug.',
      row: 11,
      col: 7,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_sein_d',
      answer: 'SEIN',
      clue: 'Grundbegriff der Ontologie.',
      row: 11,
      col: 11,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_dasein_d',
      answer: 'DASEIN',
      clue: 'Heideggers Wort für menschliche Existenz.',
      row: 9,
      col: 11,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_rede_a',
      answer: 'REDE',
      clue: 'Gesprochenes Wort; wichtig im Dialog.',
      row: 9,
      col: 9,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_norm_a',
      answer: 'NORM',
      clue: 'Maßstab dafür, was gelten oder geschehen soll.',
      row: 14,
      col: 11,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_welt_d',
      answer: 'WELT',
      clue: 'Bei Wittgenstein: alles, was der Fall ist.',
      row: 0,
      col: 5,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_moral_a',
      answer: 'MORAL',
      clue: 'Regeln und Maßstäbe des Handelns.',
      row: 2,
      col: 1,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_leere_d',
      answer: 'LEERE',
      clue: 'Wichtiges Motiv im Buddhismus.',
      row: 5,
      col: 12,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_raum_d',
      answer: 'RAUM',
      clue: 'Bei Kant eine Form der Anschauung.',
      row: 10,
      col: 7,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_mut_d',
      answer: 'MUT',
      clue: 'Tugend im Umgang mit Gefahr.',
      row: 2,
      col: 1,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_kraft_d',
      answer: 'KRAFT',
      clue: 'Vermögen zu wirken.',
      row: 1,
      col: 3,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_stoff_a',
      answer: 'STOFF',
      clue: 'Materielles Prinzip im Gegensatz zur Form.',
      row: 4,
      col: 0,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_sorge_d',
      answer: 'SORGE',
      clue: 'Grundstruktur des Daseins bei Heidegger.',
      row: 4,
      col: 0,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_zeit_a',
      answer: 'ZEIT',
      clue: 'Grundform der Erfahrung neben dem Raum.',
      row: 7,
      col: 11,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_satz_d',
      answer: 'SATZ',
      clue: 'Aussage aus Wörtern; in der Logik wichtig.',
      row: 5,
      col: 14,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_kant_d',
      answer: 'KANT',
      clue: 'Philosoph des kategorischen Imperativs.',
      row: 1,
      col: 10,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_akt_a',
      answer: 'AKT',
      clue: 'Vollzug im Gegensatz zur Möglichkeit.',
      row: 2,
      col: 10,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_scham_a',
      answer: 'SCHAM',
      clue: 'Moralischer Affekt der Selbstbewertung.',
      row: 13,
      col: 3,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_these_d',
      answer: 'THESE',
      clue: 'Behauptung oder Ausgangssatz.',
      row: 10,
      col: 3,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_synthese_d',
      answer: 'SYNTHESE',
      clue: 'Zusammenführung von Gegensätzen.',
      row: 7,
      col: 3,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_arche_d',
      answer: 'ARCHE',
      clue: 'Griechisch: Anfang oder Urprinzip.',
      row: 10,
      col: 5,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_stoa_a',
      answer: 'STOA',
      clue: 'Antike Schule der Gelassenheit.',
      row: 10,
      col: 2,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_hyle_a',
      answer: 'HYLE',
      clue: 'Griechisch: Stoff oder Materie.',
      row: 12,
      col: 0,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_eros_a',
      answer: 'EROS',
      clue: 'Bei Platon: Liebe oder Begehren.',
      row: 12,
      col: 11,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_dike_a',
      answer: 'DIKE',
      clue: 'Griechisch: Recht oder Gerechtigkeit.',
      row: 14,
      col: 0,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_gut_d',
      answer: 'GUT',
      clue: 'Zentraler Wertbegriff der Ethik.',
      row: 0,
      col: 12,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_agon_a',
      answer: 'AGON',
      clue: 'Griechisch: Streit oder Wettkampf.',
      row: 0,
      col: 11,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_ren_a',
      answer: 'REN',
      clue: 'Konfuzianische Menschlichkeit.',
      row: 6,
      col: 0,
      direction: WordDirection.across,
    ),
    const CrosswordWord(
      id: 'kompakt_dao_d',
      answer: 'DAO',
      clue: 'Weg oder Grundprinzip im Daoismus.',
      row: 10,
      col: 13,
      direction: WordDirection.down,
    ),
    const CrosswordWord(
      id: 'kompakt_nous_d',
      answer: 'NOUS',
      clue: 'Griechisch für Geist oder Vernunft.',
      row: 0,
      col: 14,
      direction: WordDirection.down,
    ),
  ],
);

final List<CrosswordPuzzle> kCrosswordPuzzles = [
  puzzleDemoKompakt,
  puzzleDemoDicht,
];
