"""Extract correct answers + categories from questions_seed.dart.

Output: JSON list with { word, category, prompt, attribution, difficulty }.
The crossword tool ingests this directly.
"""
import json
import re
from pathlib import Path

SEED = Path(__file__).resolve().parent.parent / "lib" / "data" / "seed" / "questions_seed.dart"
OUT  = Path(__file__).resolve().parent.parent / "crossword-builder" / "data" / "answers.json"

text = SEED.read_text(encoding="utf-8")

# Each Question(...) block ends with ),\n   followed by another Question or close.
# We split on "Question(" and parse the fields with regex per block.
blocks = text.split("Question(")[1:]

def unescape_dart(s: str) -> str:
    # Handle the Dart escape sequences that actually appear in the seed file.
    return (s.replace("\\'", "'")
             .replace('\\"', '"')
             .replace("\\n", "\n")
             .replace("\\\\", "\\"))

def field(block: str, name: str) -> str | None:
    # match "name: '...'" or "name: \"...\"" — Dart strings can be single or double quoted.
    m = re.search(rf"{name}:\s*'((?:[^'\\]|\\.)*)'", block)
    if m: return unescape_dart(m.group(1))
    m = re.search(rf'{name}:\s*"((?:[^"\\]|\\.)*)"', block)
    if m: return unescape_dart(m.group(1))
    return None

def options(block: str) -> list[str]:
    m = re.search(r"options:\s*\[(.+?)\]", block, re.DOTALL)
    if not m: return []
    raw = m.group(1)
    # Match each quoted string, single or double.
    out = []
    for s in re.finditer(r"'((?:[^'\\]|\\.)*)'|\"((?:[^\"\\]|\\.)*)\"", raw):
        s_val = s.group(1) if s.group(1) is not None else s.group(2)
        out.append(unescape_dart(s_val))
    return out

def correct_index(block: str) -> int | None:
    m = re.search(r"correctIndex:\s*(\d+)", block)
    return int(m.group(1)) if m else None

def difficulty(block: str) -> int | None:
    m = re.search(r"difficulty:\s*(\d+)", block)
    return int(m.group(1)) if m else None

def category(block: str) -> str | None:
    m = re.search(r"category:\s*QuestionCategory\.(\w+)", block)
    return m.group(1) if m else None

CATEGORY_LABELS = {
    "quoteToPhilosopher":  "Zitat → Philosoph",
    "workToAuthor":        "Werk → Autor",
    "philosopherToEra":    "Philosoph → Epoche",
    "conceptToSchool":     "Begriff → Schule",
    "completeQuote":       "Zitat vervollständigen",
    "whoCriticizedWhom":   "Kritik & Streit",
}

entries = []
seen_words = set()
for block in blocks:
    opts = options(block)
    ci = correct_index(block)
    if ci is None or ci >= len(opts):
        continue
    answer = opts[ci]
    cat = category(block)
    cat_label = CATEGORY_LABELS.get(cat, cat or "")
    entries.append({
        "word": answer,
        "category": cat_label,
        "categoryKey": cat,
        "prompt": field(block, "prompt") or "",
        "attribution": field(block, "attribution") or "",
        "difficulty": difficulty(block) or 0,
        "philosopherId": field(block, "philosopherId") or "",
    })

# De-dup by (word, category) but keep the first prompt per word.
unique = {}
for e in entries:
    key = e["word"].strip()
    if not key:
        continue
    if key not in unique:
        unique[key] = e
        unique[key]["prompts"] = []
    if e["prompt"]:
        unique[key]["prompts"].append({
            "prompt": e["prompt"],
            "category": e["category"],
            "attribution": e["attribution"],
            "difficulty": e["difficulty"],
        })

result = sorted(unique.values(), key=lambda x: x["word"].lower())
for r in result:
    r.pop("prompt", None)
    r.pop("attribution", None)
    r.pop("difficulty", None)
    r.pop("categoryKey", None)
    r.pop("philosopherId", None)

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")

# Also write data.js so the HTML tool works under file:// without fetch().
JS_OUT = OUT.parent / "data.js"
JS_OUT.write_text(
    "// Auto-generated by scripts/extract_answers.py — do not edit.\n"
    "window.SOPHIA_ANSWERS = "
    + json.dumps(result, ensure_ascii=False, indent=2)
    + ";\n",
    encoding="utf-8",
)
print(f"Wrote {len(result)} unique answers to {OUT}")
print(f"Wrote {len(result)} unique answers to {JS_OUT}")
