"""Extract the full question pool from questions_seed.dart into JSON.

Used by the local CMS (cms/) — provides a machine-friendly structure that
the editor reads in, then writes back via write_questions.py.

Output: cms/data/questions.json + cms/data/philosophers.json
"""
import json
import re
from pathlib import Path

ROOT       = Path(__file__).resolve().parent.parent
SEED       = ROOT / "lib" / "data" / "seed" / "questions_seed.dart"
PHIL_SEED  = ROOT / "lib" / "data" / "seed" / "philosophers_seed.dart"
OUT_DIR    = ROOT / "cms" / "data"


def unescape_dart(s: str) -> str:
    return (s.replace("\\'", "'")
             .replace('\\"', '"')
             .replace("\\n", "\n")
             .replace("\\\\", "\\"))


def find_quoted(name: str, block: str) -> str | None:
    """Return the unescaped value of `name: '...'` or `name: "..."`."""
    m = re.search(rf"{name}:\s*'((?:[^'\\]|\\.)*)'", block)
    if m:
        return unescape_dart(m.group(1))
    m = re.search(rf'{name}:\s*"((?:[^"\\]|\\.)*)"', block)
    if m:
        return unescape_dart(m.group(1))
    return None


def find_options(block: str) -> list[str]:
    m = re.search(r"options:\s*\[(.+?)\]", block, re.DOTALL)
    if not m:
        return []
    raw = m.group(1)
    out: list[str] = []
    for s in re.finditer(r"'((?:[^'\\]|\\.)*)'|\"((?:[^\"\\]|\\.)*)\"", raw):
        s_val = s.group(1) if s.group(1) is not None else s.group(2)
        out.append(unescape_dart(s_val))
    return out


def find_int(name: str, block: str) -> int | None:
    m = re.search(rf"{name}:\s*(\d+)", block)
    return int(m.group(1)) if m else None


def find_enum(name: str, enum_prefix: str, block: str) -> str | None:
    m = re.search(rf"{name}:\s*{re.escape(enum_prefix)}\.(\w+)", block)
    return m.group(1) if m else None


# ─────────────────────────── Questions ───────────────────────────


def extract_questions() -> list[dict]:
    text = SEED.read_text(encoding="utf-8")
    blocks = text.split("Question(")[1:]
    out: list[dict] = []
    for block in blocks:
        # Cut at the matching close paren of this Question literal — naive
        # but works because Question(...) blocks don't nest in this seed.
        # We rely on the next "Question(" or end-of-list as delimiter; the
        # split has already done that.
        q = {
            "id":            find_quoted("id", block),
            "category":      find_enum("category", "QuestionCategory", block),
            "prompt":        find_quoted("prompt", block),
            "options":       find_options(block),
            "correctIndex":  find_int("correctIndex", block),
            "difficulty":    find_int("difficulty", block),
            "attribution":   find_quoted("attribution", block),
            "explanation":   find_quoted("explanation", block),
            "philosopherId": find_quoted("philosopherId", block),
            "topicKey":      find_quoted("topicKey", block),
        }
        if q["id"] is None or q["category"] is None:
            continue
        out.append(q)
    return out


# ─────────────────────────── Philosophers ───────────────────────────


def find_aliases(block: str) -> list[str]:
    m = re.search(r"aliases:\s*\[(.*?)\]", block, re.DOTALL)
    if not m:
        return []
    raw = m.group(1)
    out: list[str] = []
    for s in re.finditer(r"'((?:[^'\\]|\\.)*)'|\"((?:[^\"\\]|\\.)*)\"", raw):
        s_val = s.group(1) if s.group(1) is not None else s.group(2)
        out.append(unescape_dart(s_val))
    return out


def extract_philosophers() -> list[dict]:
    text = PHIL_SEED.read_text(encoding="utf-8")
    blocks = text.split("Philosopher(")[1:]
    out: list[dict] = []
    for block in blocks:
        out.append({
            "id":         find_quoted("id", block),
            "name":       find_quoted("name", block),
            "years":      find_quoted("years", block),
            "era":        find_enum("era", "Era", block),
            "school":     find_quoted("school", block),
            "tagline":    find_quoted("tagline", block),
            "imageAsset": find_quoted("imageAsset", block),
            "aliases":    find_aliases(block),
        })
    return [p for p in out if p["id"]]


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    questions = extract_questions()
    payload = {"version": 1, "questions": questions}
    (OUT_DIR / "questions.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    # Also dump as JS for file:// load without fetch().
    (OUT_DIR / "questions.js").write_text(
        "// Auto-generated by scripts/extract_questions.py — do not edit.\n"
        "window.ELEUTHERIA_QUESTIONS = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )

    philosophers = extract_philosophers()
    (OUT_DIR / "philosophers.json").write_text(
        json.dumps(philosophers, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (OUT_DIR / "philosophers.js").write_text(
        "// Auto-generated by scripts/extract_questions.py — do not edit.\n"
        "window.ELEUTHERIA_PHILOSOPHERS = "
        + json.dumps(philosophers, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )

    print(f"Wrote {len(questions)} questions -> {OUT_DIR / 'questions.json'}")
    print(f"Wrote {len(philosophers)} philosophers -> {OUT_DIR / 'philosophers.json'}")


if __name__ == "__main__":
    main()
